# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-24 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180824_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlist',
            name='year',
        ),
    ]
